# Prometheus configuration for AI Platform monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'ai-platform'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/api/metrics'
    params:
      format: ['prometheus']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Puedes añadir más jobs para otros servicios
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']